/**
 * deploy.ts — OpenEscrow contracts/scripts
 *
 * Hardhat deployment script for OpenEscrow on Sepolia testnet.
 * Handles: deploying OpenEscrow.sol with USDC and USDT token addresses,
 *          logging the deployed contract address, and exporting the ABI
 *          to packages/shared/src/abis/OpenEscrow.json.
 * Does NOT: deploy mock tokens, verify on Etherscan automatically
 *           (run `hardhat verify` separately), or interact with the contract
 *           post-deployment.
 *
 * Usage:
 *   pnpm deploy:sepolia
 *   (from contracts/ directory, or via turbo from repo root)
 *
 * Required env vars (sourced from .env at repo root):
 *   SEPOLIA_RPC_URL           — RPC endpoint for Sepolia
 *   DEPLOYER_PRIVATE_KEY      — Deployer wallet private key (no 0x prefix needed)
 *   SEPOLIA_USDC_ADDRESS      — USDC token contract address on Sepolia
 *   SEPOLIA_USDT_ADDRESS      — USDT token contract address on Sepolia
 */

import { ethers, artifacts } from 'hardhat';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Main deployment function. Reads token addresses from env, deploys the contract,
 * and exports the ABI to the shared package.
 *
 * @returns Promise that resolves when deployment and ABI export are complete.
 * @throws {Error} If required env vars are missing or deployment fails.
 */
async function main(): Promise<void> {
  const usdcAddress = process.env['SEPOLIA_USDC_ADDRESS'];
  const usdtAddress = process.env['SEPOLIA_USDT_ADDRESS'];

  if (!usdcAddress) {
    throw new Error('Missing env var: SEPOLIA_USDC_ADDRESS');
  }
  if (!usdtAddress) {
    throw new Error('Missing env var: SEPOLIA_USDT_ADDRESS');
  }

  console.log('[deploy] Starting OpenEscrow deployment...');
  console.log(`[deploy] Network: ${(await ethers.provider.getNetwork()).name}`);
  console.log(`[deploy] USDC address: ${usdcAddress}`);
  console.log(`[deploy] USDT address: ${usdtAddress}`);

  const [deployer] = await ethers.getSigners();
  if (!deployer) throw new Error('No deployer signer found — check DEPLOYER_PRIVATE_KEY env var');

  console.log(`[deploy] Deployer: ${deployer.address}`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`[deploy] Deployer balance: ${ethers.formatEther(balance)} ETH`);

  if (balance === 0n) {
    throw new Error('Deployer has zero ETH balance — fund the wallet before deploying');
  }

  // Deploy the contract.
  const OpenEscrowFactory = await ethers.getContractFactory('OpenEscrow');
  const escrow = await OpenEscrowFactory.deploy(usdcAddress, usdtAddress);
  await escrow.waitForDeployment();

  const contractAddress = await escrow.getAddress();
  console.log(`[deploy] OpenEscrow deployed at: ${contractAddress}`);

  // Export ABI to packages/shared/src/abis/OpenEscrow.json.
  await exportAbi(contractAddress);

  console.log('[deploy] Deployment complete.');
  console.log(`[deploy] To verify on Etherscan:`);
  console.log(`  npx hardhat verify --network sepolia ${contractAddress} ${usdcAddress} ${usdtAddress}`);
}

/**
 * Reads the compiled artifact, writes the ABI to packages/shared/src/abis/OpenEscrow.json,
 * and updates packages/shared/src/abis/index.ts to export the ABI.
 *
 * @param contractAddress - The deployed contract address (included in the export for reference).
 * @returns Promise that resolves when the ABI file is written.
 * @throws {Error} If the artifact cannot be read or the target directory does not exist.
 */
async function exportAbi(contractAddress: string): Promise<void> {
  // Resolve the shared package path relative to this script.
  const sharedAbisDir = path.resolve(__dirname, '../../packages/shared/src/abis');

  if (!fs.existsSync(sharedAbisDir)) {
    throw new Error(`Target ABI directory does not exist: ${sharedAbisDir}`);
  }

  // Read the compiled artifact.
  const artifact = await artifacts.readArtifact('OpenEscrow');

  // Write ABI + metadata to the shared package.
  const exportData = {
    _comment: 'Auto-generated by contracts/scripts/deploy.ts — do not edit manually',
    contractName: artifact.contractName,
    deployedAddress: contractAddress,
    abi: artifact.abi,
  };

  const abiOutPath = path.join(sharedAbisDir, 'OpenEscrow.json');
  fs.writeFileSync(abiOutPath, JSON.stringify(exportData, null, 2) + '\n', 'utf-8');
  console.log(`[deploy] ABI exported to: ${abiOutPath}`);
}

// Execute.
main()
  .then(() => process.exit(0))
  .catch((err: unknown) => {
    console.error('[deploy] Deployment failed:', err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
