/**
 * deploy.ts — OpenEscrow contracts/scripts
 *
 * Deployment script for OpenEscrowV1 via UUPS proxy pattern.
 * Handles: deploying the implementation + ERC-1967 proxy via OpenZeppelin upgrades,
 *          logging deployed addresses, and exporting the ABI to packages/shared.
 * Does NOT: deploy mock tokens, run Etherscan verification automatically
 *           (run `hardhat verify` separately), or interact with the contract
 *           post-deployment.
 *
 * Usage (from contracts/ or via turbo from repo root):
 *   pnpm deploy:sepolia    — deploy to Sepolia testnet
 *   pnpm deploy:mainnet   — deploy to Ethereum mainnet
 *   pnpm deploy:bsc       — deploy to BNB Smart Chain
 *   pnpm deploy:polygon   — deploy to Polygon
 *
 * Required env vars (sourced from root .env):
 *   USDC_ADDRESS          — USDC token contract address on the target network
 *   USDT_ADDRESS          — USDT token contract address on the target network
 *   DEPLOYER_PRIVATE_KEY  — Deployer wallet private key
 *   <NETWORK>_RPC_URL     — RPC endpoint for the target network
 *
 * After deployment, save PROXY_ADDRESS to .env as CONTRACT_ADDRESS.
 */

import { ethers, upgrades, artifacts } from 'hardhat';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Main deployment entry point. Reads token addresses from env, deploys the UUPS proxy,
 * and exports the ABI to the shared package.
 *
 * @returns Promise that resolves when deployment and ABI export are complete.
 * @throws {Error} If required env vars are missing or deployment fails.
 */
async function main(): Promise<void> {
  const usdcAddress = process.env['USDC_ADDRESS'];
  const usdtAddress = process.env['USDT_ADDRESS'];

  if (!usdcAddress) {
    throw new Error('Missing env var: USDC_ADDRESS');
  }
  if (!usdtAddress) {
    throw new Error('Missing env var: USDT_ADDRESS');
  }

  const network = await ethers.provider.getNetwork();
  console.log('[deploy] Starting OpenEscrowV1 UUPS proxy deployment...');
  console.log(`[deploy] Network: ${network.name} (chainId: ${network.chainId})`);
  console.log(`[deploy] USDC address: ${usdcAddress}`);
  console.log(`[deploy] USDT address: ${usdtAddress}`);

  const [deployer] = await ethers.getSigners();
  if (!deployer) throw new Error('No deployer signer found — check DEPLOYER_PRIVATE_KEY env var');
  console.log(`[deploy] Deployer: ${deployer.address}`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`[deploy] Deployer balance: ${ethers.formatEther(balance)} ETH`);
  if (balance === 0n) {
    throw new Error('Deployer has zero ETH balance — fund the wallet before deploying');
  }

  // Deploy the UUPS proxy.
  // upgrades.deployProxy deploys the implementation + ERC-1967 proxy in one transaction.
  // The proxy address is what you set as CONTRACT_ADDRESS in your .env.
  const OpenEscrowV1Factory = await ethers.getContractFactory('OpenEscrowV1');
  const proxy = await upgrades.deployProxy(OpenEscrowV1Factory, [usdcAddress, usdtAddress], {
    initializer: 'initialize',
    kind: 'uups',
  });
  await proxy.waitForDeployment();

  const proxyAddress = await proxy.getAddress();
  const implAddress = await upgrades.erc1967.getImplementationAddress(proxyAddress);

  console.log(`[deploy] Proxy (CONTRACT_ADDRESS) deployed at: ${proxyAddress}`);
  console.log(`[deploy] Implementation deployed at:           ${implAddress}`);

  // Export ABI from the implementation artifact to packages/shared.
  await exportAbi(proxyAddress);

  console.log('[deploy] Deployment complete.');
  console.log('[deploy] Next steps:');
  console.log(`  1. Update .env: CONTRACT_ADDRESS=${proxyAddress}`);
  console.log(`  2. Update .env: NEXT_PUBLIC_CONTRACT_ADDRESS=${proxyAddress}`);
  console.log(`  3. Verify the IMPLEMENTATION (not the proxy) on the block explorer:`);
  console.log(`     npx hardhat verify --network sepolia ${implAddress}`);
  console.log(`  4. On Etherscan: open the PROXY address → Contract → "Is this a Proxy?" → Save`);
  console.log(`     This links the proxy to the verified implementation so the full ABI is shown.`);
}

/**
 * Reads the compiled OpenEscrowV1 artifact and writes the ABI to
 * packages/shared/src/abis/OpenEscrow.json (keeping the consumer-facing filename stable).
 *
 * @param proxyAddress - The deployed proxy address (included in the export for reference).
 * @returns Promise that resolves when the ABI file is written.
 * @throws {Error} If the artifact cannot be read or the target directory does not exist.
 */
async function exportAbi(proxyAddress: string): Promise<void> {
  const sharedAbisDir = path.resolve(__dirname, '../../packages/shared/src/abis');
  if (!fs.existsSync(sharedAbisDir)) {
    throw new Error(`Target ABI directory does not exist: ${sharedAbisDir}`);
  }

  const artifact = await artifacts.readArtifact('OpenEscrowV1');

  const exportData = {
    _comment: 'Auto-generated by contracts/scripts/deploy.ts — do not edit manually',
    contractName: artifact.contractName,
    deployedAddress: proxyAddress,
    abi: artifact.abi,
  };

  const abiOutPath = path.join(sharedAbisDir, 'OpenEscrow.json');
  fs.writeFileSync(abiOutPath, JSON.stringify(exportData, null, 2) + '\n', 'utf-8');
  console.log(`[deploy] ABI exported to: ${abiOutPath}`);
}

main()
  .then(() => process.exit(0))
  .catch((err: unknown) => {
    console.error('[deploy] Deployment failed:', err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
