/**
 * export-abi.ts — OpenEscrow contracts/scripts
 *
 * Standalone script to export the compiled OpenEscrow ABI to packages/shared.
 * Handles: reading the Hardhat artifact, writing OpenEscrow.json to the shared
 *          abis directory, and updating the abis/index.ts export file.
 * Does NOT: deploy contracts, interact with any network, or write TypeScript types
 *           (those are in the types/ directory, maintained by contracts-agent).
 *
 * Usage (run after `pnpm build` in contracts/):
 *   npx ts-node scripts/export-abi.ts
 *   OR: pnpm hardhat run scripts/export-abi.ts
 */

import { artifacts } from 'hardhat';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Reads the compiled artifact and exports the ABI to packages/shared/src/abis/.
 * Also updates packages/shared/src/abis/index.ts with the export statement.
 *
 * @returns Promise that resolves when all files are written.
 * @throws {Error} If the artifact is missing (run `hardhat compile` first)
 *                 or the target directory does not exist.
 */
async function exportAbi(): Promise<void> {
  const sharedAbisDir = path.resolve(__dirname, '../../packages/shared/src/abis');

  if (!fs.existsSync(sharedAbisDir)) {
    throw new Error(
      `Shared abis directory not found: ${sharedAbisDir}\nDid you run Phase 0 (repo bootstrap)?`
    );
  }

  // Read compiled artifact (requires `hardhat compile` to have been run first).
  let artifact;
  try {
    artifact = await artifacts.readArtifact('OpenEscrowV1');
  } catch (err) {
    throw new Error(
      `Could not read OpenEscrowV1 artifact. Run 'pnpm build' in contracts/ first.\n` +
        `Original error: ${err instanceof Error ? err.message : String(err)}`
    );
  }

  // Write ABI JSON.
  const exportData = {
    _comment: 'Auto-generated by contracts/scripts/export-abi.ts — do not edit manually',
    contractName: artifact.contractName,
    abi: artifact.abi,
  };

  const abiOutPath = path.join(sharedAbisDir, 'OpenEscrow.json');
  fs.writeFileSync(abiOutPath, JSON.stringify(exportData, null, 2) + '\n', 'utf-8');
  console.log(`[export-abi] Wrote: ${abiOutPath}`);

  // Update abis/index.ts to export the ABI.
  const indexPath = path.join(sharedAbisDir, 'index.ts');
  const indexContent = `/**
 * abis/index.ts — @open-escrow/shared
 *
 * Contract ABI exports for OpenEscrow.
 * Handles: exporting compiled Solidity ABIs for use by apps/api (chain indexer)
 *          and apps/web (wagmi contract hooks).
 * Does NOT: contain contract logic — see contracts/src/OpenEscrow.sol.
 *
 * Auto-generated by contracts/scripts/export-abi.ts after Phase 1 compile.
 * Re-run that script to refresh after contract changes.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
export const OpenEscrowABI = require('./OpenEscrow.json') as {
  contractName: string;
  abi: readonly object[];
};
`;
  fs.writeFileSync(indexPath, indexContent, 'utf-8');
  console.log(`[export-abi] Updated: ${indexPath}`);

  console.log('[export-abi] ABI export complete.');
}

exportAbi()
  .then(() => process.exit(0))
  .catch((err: unknown) => {
    console.error('[export-abi] Failed:', err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
