/**
 * abis/index.ts — @open-escrow/shared
 *
 * Contract ABI exports for OpenEscrow.
 * Handles: exporting compiled Solidity ABIs for use by apps/api (chain indexer)
 *          and apps/web (wagmi contract hooks).
 * Does NOT: contain contract logic — see contracts/src/OpenEscrow.sol.
 *
 * Auto-generated by contracts/scripts/export-abi.ts after Phase 1 compile.
 * Re-run that script to refresh after contract changes.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
export const OpenEscrowABI = require('./OpenEscrow.json') as {
  contractName: string;
  abi: readonly object[];
};
